@startuml

title Concept Classes Diagram 



Class Writer
Class SomnologistDoctor
Class Writing

Writer"1" --> "*" Writing : Creates >

Writer"*" <-- "*" SomnologistDoctor : Provides information <

@enduml
